name: Generate ascii workflow

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7


            - name: Executing shell script
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh

            - name: Upload dragon test file
              uses: actions/upload-artifact@v7
              with:
                name: dragon-text-file
                path: dragon.txt # or path/to/artifact

    test_job2:
        needs: ascii_job
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10 seconds
              run: sleep 10

            - name: List all files & directories
              run: ls -la

            - name: Download dragon text file
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-file


    deploy_job3:
        needs: test_job2
        runs-on: ubuntu-latest
        steps: 
            - name: Download dragon text file
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-file

            - name: Deploy app
              run: echo "Deploying app..."

      