name: Used variables and secrets in Docker

on: push

env:
    CONTAINER_REGISTRY: docker.io
    #DOCKER_USERNAME: nayakdocker
    IMAGE_NAME: github-actions-nginx

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
        - name: Docker Build
          run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker login
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}